# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112HF8BaVJpP-VGDyltgSogKW3ZnKZAxJ
"""

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import DataLoader, TensorDataset

# 1. DATA ACQUISITION & PREPROCESSING
def generate_multivariate_data(n_steps=1200):
    """Generates a synthetic multivariate time series with 5 correlated variables."""
    t = np.linspace(0, 100, n_steps)
    # Creating complex dependencies
    v1 = np.sin(t) + np.random.normal(0, 0.1, n_steps)
    v2 = np.cos(t * 0.5) + v1 * 0.5
    v3 = np.sin(t * 0.2) * v2
    v4 = v1**2 + np.random.normal(0, 0.05, n_steps)
    v5 = v1 + v2 - v3 + np.random.normal(0, 0.1, n_steps)

    data = pd.DataFrame({'v1': v1, 'v2': v2, 'v3': v3, 'v4': v4, 'target': v5})
    return data

data = generate_multivariate_data()
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

def create_sequences(data, seq_length):
    xs, ys = [], []
    for i in range(len(data) - seq_length):
        xs.append(data[i:i+seq_length, :])
        ys.append(data[i+seq_length, -1]) # Predicting the 'target' column
    return np.array(xs), np.array(ys)

SEQ_LENGTH = 24
X, y = create_sequences(scaled_data, SEQ_LENGTH)
train_size = int(len(X) * 0.8)

X_train = torch.FloatTensor(X[:train_size])
y_train = torch.FloatTensor(y[:train_size])
X_test = torch.FloatTensor(X[train_size:])
y_test = torch.FloatTensor(y[train_size:])

# 2. CUSTOM MODEL ARCHITECTURE (ATTENTION + LSTM)
class AttentionBlock(nn.Module):
    def __init__(self, hidden_dim):
        super(AttentionBlock, self).__init__()
        self.attention = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1)
        )

    def forward(self, lstm_output):
        # lstm_output shape: [batch, seq_len, hidden_dim]
        weights = self.attention(lstm_output) # [batch, seq_len, 1]
        weights = torch.softmax(weights, dim=1)
        context = torch.sum(weights * lstm_output, dim=1) # [batch, hidden_dim]
        return context, weights

class TimeSeriesModel(nn.Module):
    def __init__(self, n_features, hidden_dim, n_layers):
        super(TimeSeriesModel, self).__init__()
        self.lstm = nn.LSTM(n_features, hidden_dim, n_layers, batch_first=True, dropout=0.2)
        self.attention = AttentionBlock(hidden_dim)
        self.fc = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        context, weights = self.attention(lstm_out)
        out = self.fc(context)
        return out, weights

# 3. BASELINE MODEL (Simple LSTM)
class BaselineLSTM(nn.Module):
    def __init__(self, n_features, hidden_dim):
        super(BaselineLSTM, self).__init__()
        self.lstm = nn.LSTM(n_features, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        _, (hn, _) = self.lstm(x)
        return self.fc(hn[-1]), None

# 4. TRAINING & HYPERPARAMETER TUNING
def train_model(model, train_loader, epochs=50, lr=0.001):
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    for epoch in range(epochs):
        for inputs, targets in train_loader:
            optimizer.zero_grad()
            outputs, _ = model(inputs)
            loss = criterion(outputs.squeeze(), targets)
            loss.backward()
            optimizer.step()

model_att = TimeSeriesModel(n_features=5, hidden_dim=64, n_layers=2)
model_base = BaselineLSTM(5, 64)

train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=32, shuffle=True)
train_model(model_att, train_loader)
train_model(model_base, train_loader)

# 5. EVALUATION
model_att.eval()
with torch.no_grad():
    preds_att, weights = model_att(X_test)
    preds_base, _ = model_base(X_test)

mse = nn.MSELoss()
rmse_att = torch.sqrt(mse(preds_att.squeeze(), y_test)).item()
rmse_base = torch.sqrt(mse(preds_base.squeeze(), y_test)).item()

print(f"Attention Model RMSE: {rmse_att:.4f}")
print(f"Baseline Model RMSE: {rmse_base:.4f}")